export default function PaymentEscrowTermsPage() {
  return (
    <section className="bg-white">
      <div className="mx-auto max-w-4xl px-6 py-16 text-neutral-900">
        <h1 className="text-3xl font-bold mb-2">
          Visibuy Payment &amp; Escrow Terms
        </h1>
        <p className="text-sm text-neutral-500 mb-8">
          Last Updated: 10th January, 2026
        </p>

        <p className="mb-6">
          These Payment &amp; Escrow Terms (“Payment Terms”) govern the use of
          payment-related features on the Visibuy platform, including
          escrow-enabled verifications facilitated through regulated third-party
          payment providers.
        </p>

        <p className="mb-10">
          By using any payment or escrow feature on Visibuy, you agree to these
          Payment Terms in addition to the Visibuy Terms &amp; Conditions.
        </p>

        {/* 1 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          1. Role of Visibuy in Payments
        </h2>
        <p className="mb-3">
          Visibuy provides a technology layer that enables buyers and sellers to
          access payment and escrow services offered by regulated third-party
          payment providers.
        </p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>
            Visibuy is not a bank, money service business, or financial
            institution.
          </li>
          <li>Visibuy does not hold, store, or control user funds.</li>
          <li>
            All payments are processed, held, and released by third-party
            payment providers in accordance with their own terms and regulatory
            obligations.
          </li>
        </ul>

        {/* 2 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          2. Payment Providers
        </h2>
        <p className="mb-3">
          Payment and escrow services on Visibuy are provided by regulated
          payment partners, which may include Flutterwave or other licensed
          providers.
        </p>
        <p className="mb-2">Users acknowledge that:</p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>
            Payment providers operate under their own terms, privacy policies,
            and compliance requirements.
          </li>
          <li>
            Visibuy does not control payment authorization, settlement,
            chargebacks, or refunds.
          </li>
        </ul>

        {/* 3 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          3. Escrow Functionality
        </h2>

        <h3 className="font-semibold mt-4 mb-2">3.1 Optional Escrow</h3>
        <p className="mb-2">
          Escrow is an optional feature that sellers may enable on a
          per-verification basis.
        </p>
        <p className="mb-2">When escrow is enabled:</p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>Buyer funds are paid directly to the payment provider</li>
          <li>
            Funds are held in accordance with the provider’s escrow rules
          </li>
          <li>Funds are not accessible to Visibuy</li>
        </ul>

        <h3 className="font-semibold mt-4 mb-2">
          3.2 Escrow Release Conditions
        </h3>
        <p className="mb-2">
          Subject to payment provider policies, escrowed funds may be released:
        </p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>Upon buyer confirmation of receipt</li>
          <li>
            Upon expiration of a defined confirmation or inspection period
          </li>
          <li>
            As otherwise determined by the payment provider’s dispute resolution
            process
          </li>
        </ul>
        <p>Visibuy does not independently release or withhold funds.</p>

        {/* 4 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          4. Non-Exclusive Verification Links &amp; Payments
        </h2>
        <p className="mb-2">
          Verification links generated by Visibuy are informational and
          non-exclusive.
        </p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>
            Sharing a verification link does not reserve a product or guarantee
            availability.
          </li>
          <li>
            Sellers are responsible for ensuring that escrow-enabled payments
            correspond to an actual, available product.
          </li>
          <li>
            Visibuy is not responsible for payment disputes arising from
            overselling, duplicate listings, or reuse of verification links.
          </li>
        </ul>

        {/* 5 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          5. Buyer Responsibilities
        </h2>
        <p className="mb-2">Buyers acknowledge that:</p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>
            Escrow reduces certain payment risks but does not eliminate all
            transaction risk
          </li>
          <li>
            Visual verification assists decision-making but is not a guarantee
          </li>
          <li>
            They must review verification content before completing payment
          </li>
        </ul>

        {/* 6 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          6. Seller Responsibilities
        </h2>
        <p className="mb-2">Sellers agree to:</p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>
            Enable escrow only for products that are genuinely available
          </li>
          <li>Fulfill orders promptly once payment is confirmed</li>
          <li>
            Communicate clearly with buyers regarding delivery timelines
          </li>
          <li>Resolve issues in good faith</li>
        </ul>

        {/* 7 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          7. Disputes &amp; Chargebacks
        </h2>
        <p className="mb-2">In the event of a dispute:</p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>
            Buyers and sellers must first attempt to resolve issues directly
          </li>
          <li>
            Visibuy may assist with evidence collection and review
          </li>
          <li>
            Final decisions regarding fund release, chargebacks, or refunds are
            handled by the payment provider
          </li>
        </ul>
        <p>Visibuy does not guarantee dispute outcomes.</p>

        {/* 8 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          8. Fees &amp; Commissions
        </h2>
        <p className="mb-2">Visibuy may charge:</p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>A service fee for escrow-enabled transactions</li>
          <li>
            Platform or processing fees disclosed at the time of transaction
          </li>
        </ul>
        <p>
          All fees are non-refundable unless required by law or payment provider
          policy.
        </p>

        {/* 9 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">9. Refunds</h2>
        <p className="mb-2">
          Refund eligibility and processing are governed by:
        </p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>Seller policies</li>
          <li>Payment provider rules</li>
          <li>Applicable laws</li>
        </ul>
        <p>Visibuy does not independently issue refunds.</p>

        {/* 10 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          10. Limitation of Liability
        </h2>
        <p className="mb-2">To the maximum extent permitted by law:</p>
        <ul className="list-disc pl-6 space-y-1 mb-4">
          <li>Payment delays or failures</li>
          <li>Incorrect fund releases</li>
          <li>Chargebacks or reversals</li>
          <li>Losses resulting from seller non-performance</li>
        </ul>

        {/* 11 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          11. Regulatory Compliance
        </h2>
        <p>
          Users agree to comply with all applicable payment, anti-fraud, and
          financial regulations. Visibuy reserves the right to suspend payment
          features where required to maintain compliance.
        </p>

        {/* 12 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">
          12. Changes to Payment Terms
        </h2>
        <p>
          Visibuy may update these Payment Terms periodically. Continued use of
          payment features constitutes acceptance of updated terms.
        </p>

        {/* 13 */}
        <h2 className="text-xl font-semibold mt-10 mb-3">13. Contact</h2>
        <p className="mb-1">For payment-related inquiries:</p>
        <p className="mb-1 font-medium">Visibuy Team</p>
        <a
          href="mailto:support@visibuy.com.ng"
          className="text-blue-600 underline"
        >
          support@visibuy.com.ng
        </a>
      </div>
    </section>
  );
}
